# Generated by Django 2.0.4 on 2018-12-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181214_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='avatar5.jpg', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
