# Generated by Django 2.1.5 on 2019-04-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181217_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
